apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: dev
type: Opaque
data:
  username: ZGV2dXNlcg==  # devuser
  password: ZGV2cGFzc3dvcmQ=  # devpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: dev
type: Opaque
data:
  username: ZGV2dXNlcg==  # devuser
  password: ZGV2cGFzc3dvcmQ=  # devpassword
