apiVersion: v1
kind: ConfigMap
metadata:
  name: cloud-gateway
  namespace: dev
data:
  application.yml: |
    server:
      port: 8080
    
    spring:
      application:
        name: cloud-gateway
      cloud:
        gateway:
          discovery:
            locator:
              enabled: true
              lower-case-service-id: true
          routes:
            - id: cloud-user
              uri: lb://cloud-user
              predicates:
                - Path=/api/user/**
              filters:
                - StripPrefix=2
            - id: cloud-auth
              uri: lb://cloud-auth
              predicates:
                - Path=/api/auth/**
              filters:
                - StripPrefix=2
            - id: cloud-product
              uri: lb://cloud-product
              predicates:
                - Path=/api/product/**
              filters:
                - StripPrefix=2
            - id: cloud-order
              uri: lb://cloud-order
              predicates:
                - Path=/api/order/**
              filters:
                - StripPrefix=2
            - id: cloud-promotion
              uri: lb://cloud-promotion
              predicates:
                - Path=/api/promotion/**
              filters:
                - StripPrefix=2
            - id: cloud-message
              uri: lb://cloud-message
              predicates:
                - Path=/api/message/**
              filters:
                - StripPrefix=2
            - id: cloud-job
              uri: lb://cloud-job
              predicates:
                - Path=/api/job/**
              filters:
                - StripPrefix=2
          globalcors:
            corsConfigurations:
              '[/**]':
                allowedOriginPatterns: "*"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowedHeaders: "*"
                allowCredentials: true
